import { collection } from "./src/api/collection";

await collection.drop().catch(() => null);
await collection.create();

await collection.upsert([
  {
    id: "1",
    owner_id: "user-1",
    name: "Alice Johnson",
    email: "alice@acme.com",
    age: 28,
    company: "netflix",
    active: true,
    joined_at: new Date("2024-01-15"),
  },
  {
    id: "2",
    owner_id: "user-1",
    name: "Bob Smith",
    email: "bob@acme.com",
    age: 35,
    company: "google",
    active: true,
    joined_at: new Date("2023-06-01"),
  },
  {
    id: "3",
    owner_id: "user-2",
    name: "Charlie Brown",
    email: "charlie@acme.com",
    age: 22,
    company: "apple",
    active: false,
    joined_at: new Date("2025-03-10"),
  },
  {
    id: "4",
    owner_id: "user-1",
    name: "Diana Prince",
    email: "diana@acme.com",
    age: 31,
    company: "netflix",
    active: true,
    joined_at: new Date("2023-11-20"),
  },
  {
    id: "5",
    owner_id: "user-2",
    name: "Eve Wilson",
    email: "eve@acme.com",
    age: 45,
    company: "google",
    active: false,
    joined_at: new Date("2022-08-05"),
  },
  {
    id: "6",
    owner_id: "user-2",
    name: "Frank Castle",
    email: "frank@acme.com",
    age: 19,
    company: "apple",
    active: true,
    joined_at: new Date("2025-01-02"),
  },
  {
    id: "7",
    owner_id: "user-1",
    name: "Grace Lee",
    email: "grace@acme.com",
    age: 27,
    company: "netflix",
    active: true,
    joined_at: new Date("2024-07-18"),
  },
  {
    id: "8",
    owner_id: "user-2",
    name: "Hank Pym",
    email: "hank@acme.com",
    age: 52,
    company: "google",
    active: false,
    joined_at: new Date("2021-12-30"),
  },
  {
    id: "9",
    owner_id: "user-1",
    name: "Iris West",
    email: "iris@acme.com",
    age: 29,
    company: "apple",
    active: true,
    joined_at: new Date("2024-04-22"),
  },
  {
    id: "10",
    owner_id: "user-2",
    name: "Jack Ryan",
    email: "jack@acme.com",
    age: 38,
    company: "netflix",
    active: true,
    joined_at: new Date("2023-09-14"),
  },
]);

console.log("Seeded 10 users (5 owned by user-1, 5 by user-2)");
